# Site settings
title: The Field Guide to Accessible Design
description: A practical guide for designers to making designs accessibility.
baseurl: "" # the subpath of your site, e.g. /blog/
url: /

# Build settings
markdown: kramdown
incremental: true

# Compress layout settings
compress_html:
  clippings: []
  comments: []
  endings: []
  ignore:
    envs: []
  blanklines: false
  profile: false
  startings: []


# Custom collections
collections:
  topics:
    output: false
    

# Include these files
include: [
  '.htaccess',
  'js/*.js',
  '_pages'
  ]


# Exclude these files
exclude: [
  '*.json',
  '*.log',
  '*.map',
  '*.zip',
  'js/**/*.*',
  'gulpfile.js',
  'node_modules',
  'src',
  'Gemfile',
  'Gemfile.lock'
  ]